version: '3.7'
services:
  #PHP Service
  app:
    build:
      # args:
      #   user: dds506
      #   uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: dds506-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./web:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80" 
    volumes:
      - ./web:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #MySQL Service
  db:
    image: mysql:latest
    container_name: mysql8-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - database.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql-files:/var/lib/mysql-files
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    env_file:
      - database.env
      - phpmyadmin.env
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local



